import sys
import os
import numpy as np
import pyscf
from pyscf import dft

from sldf import calc_SLDF

mol = pyscf.gto.Mole()

mol.atom = '''
H    0.00000000    0.91087015    0.53855853
H    0.00000000   -0.88833620    0.55719192
O    0.00000000    0.00000000    1.29177249
'''
mol.basis   = 'ccpvtz'
mol.verbose = 10
mol.output  = 'pyscf.log'
mol.build()

dm = pyscf.scf.hf.init_guess_by_atom(mol)

# Grid settings
grids = pyscf.dft.gen_grid.Grids(mol)
grids.atom_grid = (99, 590)
grids.prune = None
grids.build()

# Grid information
coords = grids.coords
weights = grids.weights

# AO values
ao = pyscf.dft.numint.eval_ao(mol, coords, deriv=1)

# Electron density and gradients
rho, dx_rho, dy_rho, dz_rho = pyscf.dft.numint.eval_rho(mol, ao, dm, xctype='GGA')

# Evaluate reduced density gradient, s
s = np.sqrt(dx_rho ** 2 + dy_rho ** 2 + dz_rho ** 2) / (rho ** (4/3))

nsp = 20
sldf = calc_SLDF(rho, s, weights, nsp)

np.savetxt('sldf.csv', sldf, fmt='%18.10e')

print('SLDF is')
print(sldf)

Ex_sldf = np.sum(sldf[:nsp])
Ec_sldf = np.sum(sldf[nsp:])

# Sanity check SLDF XC energies
ex, vx, _, _ = pyscf.dft.libxc.eval_xc('lda,', rho)
ec, vc, _, _ = pyscf.dft.libxc.eval_xc(',pw_mod', rho)

Ex = np.einsum('i,i,i->', ex, rho, weights)
Ec = np.einsum('i,i,i->', ec, rho, weights)

# Reference SLDF is generated by PySCF 2.10.0;
# Might be slightly different if other versions of PySCF are used
ref_sldf = np.loadtxt('ref_sldf.csv')

if not (np.allclose(Ex_sldf, Ex) and np.allclose(Ec_sldf, Ec)):
    raise ValueError("SLDF Exchange and Correlation are not consistent with LDA")
if np.allclose(ref_sldf, sldf):
    print('SLDF generation is successful!')
    print('SLDF is saved to sldf.csv')
    print(f'Sum of Exchange SLDF = {Ex_sldf:.3f}')
    print(f'Sum of Correlation SLDF = {Ec_sldf:.3f}')
else:
    print('SLDF generation is not consistent with SLDF generated by PySCF 2.10.0')
    print(f'Mean absolute difference is {np.mean(abs(ref_sldf - sldf)):.2e}')
